#!/bin/sh

echo "web links or youtube(w/y/t)"

read a

if [ "$a" = "w" ]; then
	echo "enter the browser you want the link open in."

	read b

	curl https://raw.githubusercontent.com/hexisXz/SSET/main/links.txt | rdrview -B $b $(fzf)
fi


if [ "$a" = "y" ]; then
	curl https://raw.githubusercontent.com/hexisXz/SSET/main/yt-links.txt | mpv $b $(fzf)
fi


if [ "$a" = "t" ]; then 
	# Extract the repository URL
	REPO_URL="https://github.com/hexisXz/SSET"

	# Fetch the repository page HTML
	HTML_CONTENT=$(curl "$REPO_URL")

	# Parse the HTML content to find directories
	echo "$HTML_CONTENT" | grep -oP '(?<=href=")[^"]+/tree/[^"]+' | awk -F'/' '{print $NF}' | sort -u
fi


#curl https://github.com/hexisXz/SSET | html2text
